GET http://localhost:8080/authors?page=0
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkYW5paWwua29yb3RhZXZAZ21haWwuY29tIiwiZXhwIjoxNjUwNTM2NjQ3fQ.syYHIduNVzjleDgqWVx70kbDP0Ptoc2SXA59hllMOSY

###

POST http://localhost:8080/authors
Content-Type: application/json

{
    "firstName": "Daniil",
    "lastName": "Daniil"
}

###

PUT http://localhost:8080/authors/21
Content-Type: application/json

{
  "firstName": "fn",
  "lastName": "ln"
}

###

DELETE http://localhost:8080/authors/21

###

GET http://localhost:8080/authors/1/posts?page=0&sort=id

###

POST http://localhost:8080/authors/1/posts
Content-Type: application/json

{
    "title": "test",
    "text": "asfsafasfirstForbiddenWordasdasfas"
}

###

PUT http://localhost:8080/authors/14/posts/3
Content-Type: application/json

{
  "title": "reading",
  "text": "reading is cool"
}

###

DELETE http://localhost:8080/authors/2/posts/4

###

GET http://localhost:8080/authors/1/posts/favorites?page=0

###

POST localhost:8080/authors/1/posts/addToFavorite?postId=2

###

POST http://localhost:8080/authors/1/posts/deleteFromFavorite?postId=1

###

POST http://localhost:8080/signIn/
Content-Type: application/json

{
  "email": "daniil.korotaev@gmail.com",
  "password": "123qwe"
}

###

POST http://localhost:8080/logout/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkYW5paWwua29yb3RhZXZAZ21haWwuY29tIiwiZXhwIjoxNjUwNTM2NjQ3fQ.syYHIduNVzjleDgqWVx70kbDP0Ptoc2SXA59hllMOSY

